// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbx6Bn5SinLMoS_1qJG_CGWT6tOBO_J7o',
    appId: '1:756511444668:web:60dd1a3cbce4a376e70ab9',
    messagingSenderId: '756511444668',
    projectId: 'creator-planner-8aad8',
    authDomain: 'creator-planner-8aad8.firebaseapp.com',
    storageBucket: 'creator-planner-8aad8.firebasestorage.app',
    measurementId: 'G-YKCDE5HC0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGsHcW9RCNkAR9ibFqMr8qWhDWZZMoVoA',
    appId: '1:756511444668:android:f09188ae47f9fa8fe70ab9',
    messagingSenderId: '756511444668',
    projectId: 'creator-planner-8aad8',
    storageBucket: 'creator-planner-8aad8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe2H1zhO6l1BO-I2i7zF8xSQhDW0JLCsM',
    appId: '1:756511444668:ios:2f0c3a774f7474a0e70ab9',
    messagingSenderId: '756511444668',
    projectId: 'creator-planner-8aad8',
    storageBucket: 'creator-planner-8aad8.firebasestorage.app',
    iosBundleId: 'com.example.creatorPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe2H1zhO6l1BO-I2i7zF8xSQhDW0JLCsM',
    appId: '1:756511444668:ios:2f0c3a774f7474a0e70ab9',
    messagingSenderId: '756511444668',
    projectId: 'creator-planner-8aad8',
    storageBucket: 'creator-planner-8aad8.firebasestorage.app',
    iosBundleId: 'com.example.creatorPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbx6Bn5SinLMoS_1qJG_CGWT6tOBO_J7o',
    appId: '1:756511444668:web:e60a8b677d78061fe70ab9',
    messagingSenderId: '756511444668',
    projectId: 'creator-planner-8aad8',
    authDomain: 'creator-planner-8aad8.firebaseapp.com',
    storageBucket: 'creator-planner-8aad8.firebasestorage.app',
    measurementId: 'G-7K6Z7HJZHV',
  );

}